In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
from statsmodels.tsa.seasonal import seasonal_decompose

In [7]:
df = pd.read_csv(r"C:\Users\admin\Downloads\Data Set For Task-20260821T102726Z-1-001\Data Set For Task\2) Stock Prices Data Set.csv")

In [9]:
df.head(10)

  symbol        date      open      high       low     close    volume
0    AAL  2014-01-02   25.0700   25.8200   25.0600   25.3600   8998943
1   AAPL  2014-01-02   79.3828   79.5756   78.8601   79.0185  58791957
2    AAP  2014-01-02  110.3600  111.8800  109.2900  109.7400    542711
3   ABBV  2014-01-02   52.1200   52.3300   51.5200   51.9800   4569061
4    ABC  2014-01-02   70.1100   70.2300   69.4800   69.8900   1148391
5    ABT  2014-01-02   38.0900   38.4000   38.0000   38.2300   4967472
6    ACN  2014-01-02   81.5000   81.9200   81.0900   81.1300   2405384
7   ADBE  2014-01-02   59.0600   59.5300   58.9400   59.2900   2746370
8    ADI  2014-01-02   49.5200   49.7500   49.0400   49.2800   2799092
9    ADM  2014-01-02   43.2200   43.2900   42.7900   42.9900   2753765

In [10]:
df["date"] = pd.to_datetime(df["date"])

In [11]:
print(df.dtypes)

symbol               str
date      datetime64[us]
open             float64
high             float64
low              float64
close            float64
volume             int64
dtype: object

In [12]:
aapl = df[df["symbol"] == "AAPL"].copy()

In [13]:
aapl.head()

     symbol       date     open     high      low    close     volume
1      AAPL 2014-01-02  79.3828  79.5756  78.8601  79.0185   58791957
484    AAPL 2014-01-03  78.9799  79.0999  77.2042  77.2828   98303870
967    AAPL 2014-01-06  76.7785  78.1142  76.2285  77.7042  103359151
1450   AAPL 2014-01-07  77.7599  77.9942  76.8464  77.1481   79432766
1933   AAPL 2014-01-08  76.9728  77.9371  76.9556  77.6371   64686685

In [14]:
print(aapl.shape)

(1007, 7)

In [15]:
aapl = aapl.sort_values("date")

In [17]:
aapl.set_index("date", inplace=True)

In [18]:
aapl.head()

           symbol     open     high      low    close     volume
date
2014-01-02   AAPL  79.3828  79.5756  78.8601  79.0185   58791957
2014-01-03   AAPL  78.9799  79.0999  77.2042  77.2828   98303870
2014-01-06   AAPL  76.7785  78.1142  76.2285  77.7042  103359151
2014-01-07   AAPL  77.7599  77.9942  76.8464  77.1481   79432766
2014-01-08   AAPL  76.9728  77.9371  76.9556  77.6371   64686685